name: lynx
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - tqdm
  - click
  - matplotlib
  - pysm3
  - emcee
  - h5py
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - jax
     - jaxlib
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
