# The name of the simulation setup, this is
# used to label the output maps in an hdf5 record.
identifier: 'so_basic'
hdf5_path: 'data/interim/so_basic.h5'
# nside at which to generate the simulations
nside: 128
# PySM models to use in the simulations
skymodel: 
  args: 
    preset_strings: 
      - 'd1'
      - 's1'
cosmo_path: 'data/planck_2018_acc.h5'
# frequencies at which to generate maps.
frequencies: [27., 39., 93., 145., 225., 280.]
# sensitivities of each channel un uK_CMB amin.
sensitivities: [35., 21., 2.6, 3.3, 6.3, 16.]
# Gaussian beam fwhm in arcmin
fwhm: [60., 60., 60., 60., 60., 60.]
monte_carlo: 200
half_mission_noise: True